### ISSUE TITLE
Don't include any constants besides those that are public for consumers outside of the module in the header file

### ISSUE THREAD

**Issue by michaeleiselsc** [eqrion/cbindgen#123]
Any constants that aren't public for consumers outside of the module shouldn't be included in the output header file. Currently, even private constants lead to `#define`s being created.

**Comment by jasongrlicky** [comment]
Hey @eqrion! Firstly, I love `cbindgen`, it has made my life so much easier when integrating Rust into my Objective-C project, so thanks to everyone who's worked on this project!

I was looking into this issue, and it seems like there's no check for visibility when parsing constants in [`Parse.load_syn_const()` in `parser.rs`](https://github.com/eqrion/cbindgen/blob/1693519e39d4578ae8af003a5f374f33b7968218/src/bindgen/parser.rs#L606), like there are for other similar functions.

Was this a purposefully omitted? If not, may I submit a PR?  I'm brand new to the codebase, but it seems like a pretty straightforward fix, so hopefully I can help out.

**Comment by eqrion** [comment]
Hi @jasongrlicky! Yes I think a check for in `parser.rs` for non `pub` visibility would be good here.

It won't be completely accurate because you can have `pub const`s inside a crate that aren't visible because they aren't `pub` from the crate root. You also can have a non `pub const` inside a `mod` that is exported by a different name with a `pub use` within that `mod` that is visible from the crate root and should be exported. Rust visibility is complicated...

But in short, I think it's reasonable to expect if someone didn't make a `const` `pub` to assume they don't want it exported.

**Comment by jasongrlicky** [comment]
Hey there! I'd feel bad about changing the behavior if people might be relying on that edge case right now (having a non-`pub const` inside a `mod` that is re-exported at the crate root). Is there be a more sophisticated way to address this than just adding a visibility check in `parser.rs` that wouldn't require a lot of changes to the way things are structured?

**Comment by jtojnar** [comment]
If visibility were supported, we could also construct [opaque structs](https://github.com/eqrion/cbindgen/issues/104) by not `pub`ing their entries.
