### ISSUE TITLE
Expand slices to separate pointer and size

### ISSUE THREAD

**Issue by kvark** [eqrion/cbindgen#247]
It would be really nice to support slices by splitting those into separate (pointer, size) values, e.g.
```rust
   objects: &[Object],
```
would be translated into:
```cpp
   objects: *const Object,
   objects_length: size_t,
```
where the "_length" suffix is configured like all the other prefixes/suffixes

**Comment by emilio** [comment]
Can you really rely on that layout and ABI?

**Comment by RReverser** [comment]
Nope.

**Comment by eqrion** [comment]
We had a discussion about this in the gfx daily. It sounds like this doesn't have a defined layout currently, but might in the future. This is another thing, like strings, where it'd be nice to be able to autogenerate conversion thunks. But there's not a great way to add support for this in cbindgen today.

So I'll close this for now.

**Comment by Manishearth** [comment]
Would it be possible for cbindgen to come with a companion library containing wrappers like `Slice`, etc which _are_ compatible? Otherwise folks have to do this per-project.

**Comment by emilio** [comment]
Ideally we'd get rust to specify [these](https://github.com/rust-lang/unsafe-code-guidelines/blob/master/reference/src/layout/pointers.md) and then just teach cbindgen about that.

But lacking them, I'd be fine with something like that. We can put it in this repo if it makes sense.

Gecko had a bunch of types for stuff like [`Box<str>`](https://searchfox.org/mozilla-central/rev/2a24205479519e70c0574929f45730d285141584/servo/components/style_traits/owned_str.rs#17), [`Box<[T]>`](https://searchfox.org/mozilla-central/rev/2a24205479519e70c0574929f45730d285141584/servo/components/style_traits/owned_slice.rs#31), etc which should be copiable pretty much straight-away. For non-owned slices I think we've been mostly passing ptr+length by hand, but a new type so that it has the right ABI would be cool...

**Comment by Manishearth** [comment]
Yeah, to be clear, cbindgen doesn't need any changes itself, it just needs to maintain a second library that works well with cbindgen that does this.

**Comment by Manishearth** [comment]
Actually, I didn't realize that cbindgen can't generate types from dependencies at all. That does make things a little bit worse here :/

**Comment by emilio** [comment]
It does generate types from dependencies, see `parse_deps = true` and `extra_bindings` if you need functions and constants from a dependent crate.

**Comment by petrochenkov** [comment]
I use the `cfg(feature = "cbindgen")` trick for this
```rust
#[repr(C)]
struct S<'a> {
    #[cfg(not(feature = "cbindgen"))]
    slice: &'a [u8],

    #[cfg(feature = "cbindgen")]
    ptr: *const u8,
    #[cfg(feature = "cbindgen")]
    len: usize,
}
```
(which is pretty useful for workarounds in general, and helps with other things like [bitfields](https://github.com/eqrion/cbindgen/blob/master/tests/rust/bitfield/src/lib.rs)).

**Comment by Manishearth** [comment]
ahhh thanks

**Comment by emilio** [comment]
Right, but that's still relying on technically unspecified behavior, isn't it? I just want https://github.com/rust-lang/unsafe-code-guidelines/blob/master/reference/src/layout/pointers.md set on stone ;)
