### ISSUE TITLE
Enable RUST_BOOTSTRAP=1 environment

### ISSUE THREAD

**Issue by kvark** [eqrion/cbindgen#344]
This would allow having `parse.expand.crates` in `cbindgen.toml` without requiring the nightly compiler. Related to #38 . Would make Gecko's life easier.
cc @eqrion @staktrace

**Comment by staktrace** [comment]
Should be `RUSTC_BOOTSTRAP=1` (not `RUST_BOOTSTRAP=1`). It's basically a hack that allows using nightly `-Z` flags on stable.

**Comment by emilio** [comment]
Why do you want to expand macros in Gecko? We wouldn't be able to do this easily anyhow, I'd think, since cbindgen runs as part of the export phase, and thus cannot depend on other compiled artifacts. 

Though maybe since it invokes rustc by itself it'd be fine.

That being said, I think it'd be better to just enable it in Gecko if we were to do this, you can do it easily changing `RunCbindgen.py` to run with the new environment variable. So I think this is wontfix, in this repo at least.

**Comment by eliaslevy** [comment]
I would be useful the documentation mentioned that `parse.expand` requires the use of the nightly compiler.

BTW, what is the reason for this?  It seems `cargo expand` works with stable.

**Comment by emilio** [comment]
`cbindgen` doesn't use `cargo expand`, it uses `rustc --pretty=expanded`.

**Comment by eliaslevy** [comment]
I am aware.  I was wondering why `cbindgen` requires `rustc` and the use of a nightly only flag while `cargo expand` seemingly performs the same function under stable.
