### ISSUE TITLE
with_define does nothing?

### ISSUE THREAD

**Issue by korken89** [eqrion/cbindgen#345]
Hi, I am trying to get around the limits of reexporting a `pub const` variable, and was thinking of manually adding the define for it (as the constant is available in another crate at compile time).

So as an extremely easy test I do the following to test how generated defines look, but no `#define` is generated:
```
    Builder::new()
        .with_crate(&crate_dir)
        .with_language(Language::Cxx)
        .with_define("test1", "test2", "test3")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("open_clib.hpp");
``` 

Have I just completely misunderstood the feature or is there an issue with the code generation?

Thanks for any assistance!

**Comment by emilio** [comment]
Yes, `with_define` is used to avoid conditional compilation, so that if you have the following Rust code:

```rust
#[cfg(feature = "foo")]
#[repr(C)]
pub struct Bar {
    pub i: i32,
};
```

You can say `with_define("feature", "foo", "FOO_ENABLED")`, and the generated code looks like:

```c
#if defined(FOO_ENABLED)
struct Bar {
  int32_t i;
};
#fi
```

What you want is better accomplished by `with_header` or `with_include`, which will either put the header in the file (so `with_header("#define FOO 32")` should do, or add an `#include` directive respectively.

Any improvements to the documentation would be deeply appreciated, sorry it was confusing to you :(
