### ISSUE TITLE
Can't find struct from other crate

### ISSUE THREAD

**Issue by dbrgn** [eqrion/cbindgen#50]
Steps to reproduce:

```
$ git clone https://github.com/dbrgn/svg2polylines
$ cd svg2polylines
$ cat >cbindgen.toml <<EOL
language = "C"

[parse]
parse_deps = true
include = ["svg2polylines"]
$ cbindgen -v svg2polylines-ffi/src/lib.rs -c cbindgen.toml -o svg2polylines.h
INFO: take ::Polyline
INFO: take ::svg_str_to_polylines
INFO: take ::free_polylines
WARN: can't find CoordinatePair
WARN: can't find size_t
WARN: can't find size_t
WARN: can't find size_t
```

The `CoordinatePair` struct is defined in the `svg2polylines` crate and is pretty simple:

```rust
/// A CoordinatePair consists of an x and y coordinate.    
#[derive(Debug, PartialEq, Copy, Clone)]    
#[cfg_attr(feature = "use_serde", derive(Serialize, Deserialize))]    
#[repr(C)]    
pub struct CoordinatePair {                                                         
    pub x: f64,    
    pub y: f64,    
}    
```

What's the reason why it can't be found?

**Comment by Michael-F-Bryan** [comment]
> What's the reason why it can't be found?

My understanding is that `cbindgen` only deals with source code and the AST. So it'll parse your crate and figure out what files it imports, but because it doesn't use the compiler under the hood it can't resolve any imports from outside your crate.

I'm not sure there's an easy fix for this short of hooking into compiler internals (I actually started writing [a guide] for doing this), which would constrain cbindgen to nightly because compiler internals are always going to be unstable.

[a guide]: https://michael-f-bryan.github.io/cargo-metrics/

**Comment by eqrion** [comment]
> What's the reason why it can't be found?

The issue here is that you are specifying a specific file, instead of a crate. This causes cbindgen to use single source mode which doesn't parse external crates (because it doesn't have context to know where external crates are). A warning here would probably be a good idea.

> My understanding is that cbindgen only deals with source code and the AST. So it'll parse your crate and figure out what files it imports, but because it doesn't use the compiler under the hood it can't resolve any imports from outside your crate.

This is partially true. cbindgen can be configured to emulate cargo and rustc's crate searching behavior, without using compiler internals. This only works with crate parsing mode, which is the bug here.

**Comment by eqrion** [comment]
Forgot to add that the command should probably be:
```bash
$ cbindgen -v svg2polylines-ffi/ -c cbindgen.toml -o svg2polylines.h
```

**Comment by eqrion** [comment]
I've added a warning for this in version `0.2.1`. Closing this for now as there is a solution.
