### ISSUE TITLE
Support Request: Using transitive dependencies

### ISSUE THREAD

**Issue by UebelAndre** [eqrion/cbindgen#626]
How do I have `cbindgen` gather all the relevant code from dependencies?

I have a small example here: https://github.com/UebelAndre/cbindgen_transitive_example

I want to generate a header file for `lib_a` that includes everything from `lib_b`. Is this possible? If so what am I doing wrong there?

**Comment by emilio** [comment]
Does `extra_bindings` in the configuration do what you want? Otherwise by default we only emit stuff for the top-level crate.

**Comment by UebelAndre** [comment]
`extra_bindings = ["lib_b"]` does work but I figured by adding `pub use lib_b::*;` to the `lib.rs` file of `lib_a` that that would be effectively including the content of `lib_b` in `lib_a`. Am I misunderstanding how visibility/this tool works? Is this possible without `extra_bindings`?

**Comment by emilio** [comment]
Not really, cbindgen is relatively dumb with regards to submodules / etc, see #7 for example. Right now `extra_bindings` is the configuration for that, and cbindgen will only look at the definition point of a given struct.

Closing now because given the comments this is working as expected, and there are issues already on file to track potential improvements.

Thanks for filing! (And if you want to improve the docs to make `extra_bindings` more discoverable, that'd be great as well)
