### ISSUE TITLE
[Question] cbindgen not declaring some types

### ISSUE THREAD

**Issue by NooneXe** [eqrion/cbindgen#668]
Sorry for noob question in advance

following code 
```rust
#[no_mangle]
pub extern fn _dummy(_l : *mut std::net::TcpStream ){} 

#[no_mangle]
pub extern fn _dummy2(_l : *mut std::string::String){} 
```

creates following C++ code:-

```rust
#pragma once

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

struct String; // why only this ? why not also TcpStream

extern "C" {

void _dummy(TcpStream *_l);

void _dummy2(String *_l);

} // extern "C"
```

My question is that why forward declaration of `std::string::String` is generated but not `std::net::TcpStream` ?
How can I generate forward declaration for `std::net::TcpStream` also ?

**Comment by emilio** [comment]
The reason is that `String` is registered specially as an opaque type:

https://github.com/eqrion/cbindgen/blob/d0d287f9f32f4b64017250c0054e2637befa1075/src/bindgen/parser.rs#L404

Blaming that it goes back to 00bf52ac. You should be able to add the forward declaration manually using the `header` config option, but I wonder if we should just treat all unresolved names as opaque...

**Comment by NooneXe** [comment]
> manually using the `header` config

Thanks :)


> treat all unresolved names as opaque

Some option to toggle such behavior would be really helpful.
