### ISSUE TITLE
Will cbindgen generate opaque types for imported structs?

### ISSUE THREAD

**Issue by vedantroy** [eqrion/cbindgen#685]
If I have:

```rust
use foo::{Bar};

pub unsafe extern "C" fn baz(x: &mut Bar) {
   // impl
}
```

will cbindgen generate an opaque type (`typedef struct Bar Bar`) for `Bar`?

I'm asking b/c it looks like cbindgen does not.

Apologies if this is in the user docs, I read through them & couldn't find an answer.

**Comment by emilio** [comment]
Generally not, because it doesn't understand the rust module system more generally, that's a very long-standing issue (#7) . You can either forward-declare them yourself with C/C++, or let cbindgen parse the dependency...

I'd totally take a PR that improves the doc on this regard, probably pointing to #7, but as of now this is expected.
