### ISSUE TITLE
`not yet implemented` panic on mp4parse_capi

### ISSUE THREAD

**Issue by rillian** [eqrion/cbindgen#79]
I tried [porting](https://github.com/rillian/mp4parse-rust/tree/cbindgen) the [mp4parse crate](https://github.com/mozilla/mp4parse-rust) from moz-cheddar today, but cbindgen panics reading the source.
```
thread 'main' panicked at 'not yet implemented', /home/giles/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.1.29/src/bindgen/mangle.rs:40:16
```

**Comment by eqrion** [comment]
I should really make the error messages more helpful.

That error means that a use of a generic couldn't be given a mangled name. For example from `Vec<u32>` to `Vec_u32` (for if Vec was `#[repr(C)]`). In mp4parse, it looks like the problematic generic is [here](https://github.com/rillian/mp4parse-rust/blob/85d8ca56ff3e060bb004d1873612cb79f444068d/mp4parse_capi/src/lib.rs#L259). Generic parameters that are references, pointers, arrays, or function pointers aren't currently supported.

The usual way around this is to use a type alias instead of the type directly. But in this case it seems like an option to a function pointer or any reference for that matter should probably emit just the pointer. That's what it looks like moz-cheddar is doing with mp4parse. I'll try and add a fix for this and better error messages.

**Comment by rillian** [comment]
Thanks for debugging! I wasn't sure where it was going wrong.

I have the impression that `Option<Fn>` is a special-case type because of the ABI guarantee of nullable-pointer representation under `#[repr(C)]`. The compiler doesn't really treat it like a generic. So supporting this seems like a helpful thing for a binding generator.

**Comment by eqrion** [comment]
Thanks for using the library!

I push version 0.1.30 which includes the change to simplify `Option<&T>` to `*T`. Wasn't able to test it yet on mp4parse, but I was able to test it on some sample files. Let me know if that resolves the issue.

**Comment by rillian** [comment]
That seems to have fixed it!

Now I get a different error. :)
```
thread 'main' panicked at 'assertion failed: !name.contains("_")', /home/giles/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.1.30/src/bindgen/mangle.rs:12:4
```

**Comment by rillian** [comment]
This seems to be caused by the [`mp4parse_indice`](https://github.com/rillian/mp4parse-rust/blob/03a9846/mp4parse_capi/src/lib.rs#L122) struct name. Not sure why it doesn't complain about the others, or with 0.1.29 and the type alias workaround.

**Comment by rillian** [comment]
It looks like `mangle_path` is supposed to be called for generic types, but it's somehow being called for the top-level `struct` type. Maybe this is because another struct has a `HashMap<u32, Vec<mp4parse_indice>>` member variable. Previously we had those in an opaque wrapper, which I'd hoped to be able to remove.

**Comment by eqrion** [comment]
Yes, `cbindgen` gathers all uses of generic structs (and unions) and generates a mangled struct (or union) for each one. So `HashMap<u32, Vec<mp4parse_indice>>` will trigger the mangling code to come up with a name for the generated struct.

Underscores are problematic because they are used in mangling the name, although I think that restriction could be lifted. Using a type alias would also eliminate that issue.

**Comment by nox** [comment]
I removed the underscores and fixed some other problems in https://github.com/mozilla/mp4parse-rust/pull/127, but there are still issues AFAIK with the generated code.

```rust
use mp4parse::MediaContext;

#[repr(C)]
pub struct Mp4parseParser {
    context: MediaContext,
    io: Mp4parseIo,
    poisoned: bool,
    opus_header: HashMap<u32, Vec<u8>>,
    pssh_data: Vec<u8>,
    sample_table: HashMap<u32, Vec<Mp4parseIndice>>,
}
```

```c++
struct HashMap_u32__Vec_Mp4parseIndice;
typedef struct HashMap_u32__Vec_Mp4parseIndice HashMap_u32__Vec_Mp4parseIndice;

struct HashMap_u32__Vec_u8;
typedef struct HashMap_u32__Vec_u8 HashMap_u32__Vec_u8;

struct Vec_u8;
typedef struct Vec_u8 Vec_u8;

typedef struct {
  intptr_t (*read)(uint8_t*, size_t, void*);
  void *userdata;
} Mp4parseIo;

typedef struct {
  MediaContext context;
  Mp4parseIo io;
  bool poisoned;
  HashMap_u32__Vec_u8 opus_header;
  Vec_u8 pssh_data;
  HashMap_u32__Vec_Mp4parseIndice sample_table;
} Mp4parseParser;
```

As you can see, `MediaContext` is completely ignored and there is no type for it; and `HashMap_u32__Vec_u8` and `HashMap_u32__Vec_Mp4parseIndice` are just forward declarations with no definitions.

**Comment by eqrion** [comment]
@nox 

So it looks like `MediaContext` isn't being found because it's defined in a different library (`mp4parse` instead of `mp4parse_capi`). You should be able to resolve this by enabling `config.parse.parse_deps`, which is disabled by default. You may need to turn on a dependency whitelist or blacklist if that causes problems. It requires a little tinkering currently.

HashMap, and Vec are only given forward declarations because they are not `#[repr(C)]`, so they can only be used by reference/pointer.

If `Mp4parseParser` is only used behind a reference/pointer, it would be easiest to remove the `#[repr(C)]` and cbindgen will just emit a forward declaration.

**Comment by rillian** [comment]
We have a working port now. Thanks for the help!
